# Generated by Django 4.1 on 2022-10-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='date',
            field=models.DateField(default='2022-01-01'),
            preserve_default=False,
        ),
    ]
