# Generated by Django 4.1 on 2022-10-05 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vaccination_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employee'),
        ),
    ]
